language: java
script: "cd A0PipeLine_Manager && ant"
install: true
jdk: oraclejdk8
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "faLLT4NTnQcTuO9vdrV5MU/1K2p7EHb5Ew1UQegKFH1GwuTPAV6vv6XKHVW/kVFog/OqnhvLIlakOImyrGIDAARSCgIiA6IsRq/rlu7U99yHo/zR7tTEA73QzIKk7OzketxcIV/s+JuXRlahbsMmkbe4jNvWbOl3If5EwHJ/un4="

addons:
  coverity_scan:
    project:
      name: "cinquin/parismi"
      description: "<Your project description here>"
    notification_email: olivier.cinquin@uci.edu
    build_command_prepend: "true"
    build_command:   "./build"
#   branch_pattern: "*"
    branch_pattern: "coverity"
