function w = weights(model)
% w = weights(model)
% Returns a column vector of length model.unsymlen
% Note: w(end) == model.b
%
% Sam Hallman, copyright 2015

w = [model.xy.w(:) ; ...
     0             ; ...
     model.xy.wm(:); ...
     model.xz.w(:) ; ...
     0             ; ...
     model.b];

assert(length(w) == model.unsymlen);
