/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pipeline_data_abstraction_and_storage_TIFFFileAccessor */

#ifndef _Included_pipeline_data_abstraction_and_storage_TIFFFileAccessor
#define _Included_pipeline_data_abstraction_and_storage_TIFFFileAccessor
#ifdef __cplusplus
extern "C" {
#endif
#undef pipeline_data_abstraction_and_storage_TIFFFileAccessor_serialVersionUID
#define pipeline_data_abstraction_and_storage_TIFFFileAccessor_serialVersionUID 1LL
#undef pipeline_data_abstraction_and_storage_TIFFFileAccessor_serialVersionUID
#define pipeline_data_abstraction_and_storage_TIFFFileAccessor_serialVersionUID 1LL
#undef pipeline_data_abstraction_and_storage_TIFFFileAccessor_serialVersionUID
#define pipeline_data_abstraction_and_storage_TIFFFileAccessor_serialVersionUID 1LL
#undef pipeline_data_abstraction_and_storage_TIFFFileAccessor_serialVersionUID
#define pipeline_data_abstraction_and_storage_TIFFFileAccessor_serialVersionUID 1LL
/*
 * Class:     pipeline_data_abstraction_and_storage_TIFFFileAccessor
 * Method:    turnOffCaching
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_pipeline_data_1abstraction_1and_1storage_TIFFFileAccessor_turnOffCaching
  (JNIEnv *, jobject, jobject);

/*
 * Class:     pipeline_data_abstraction_and_storage_TIFFFileAccessor
 * Method:    turnOnCaching
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_pipeline_data_1abstraction_1and_1storage_TIFFFileAccessor_turnOnCaching
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
